import os
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = Path(os.getenv("AI_TESTING_DATA_DIR", BACKEND_ROOT / "data")).resolve()
LOGS_DIR = Path(os.getenv("AI_TESTING_LOGS_DIR", BACKEND_ROOT / "logs")).resolve()
DB_PATH = Path(os.getenv("AI_TESTING_DB_PATH", DATA_DIR / "ai_testing.db")).resolve()
REJECTED_CASE_KNOWLEDGE_BASE_ID = os.getenv("AI_TESTING_REJECTED_CASE_KNOWLEDGE_BASE_ID", "").strip()

PROJECT_FILE_STORAGE_ROOT = Path(
    os.getenv("AI_TESTING_PROJECT_FILE_STORAGE_DIR", DATA_DIR / "projects")
).resolve()

REQUIREMENT_UPLOAD_MAX_FILES = int(os.getenv("AI_TESTING_REQUIREMENT_UPLOAD_MAX_FILES", "10"))
REQUIREMENT_UPLOAD_MAX_FILE_SIZE_BYTES = int(
    os.getenv("AI_TESTING_REQUIREMENT_UPLOAD_MAX_FILE_SIZE_MB", "20")
) * 1024 * 1024
REQUIREMENT_UPLOAD_MAX_BATCH_SIZE_BYTES = int(
    os.getenv("AI_TESTING_REQUIREMENT_UPLOAD_MAX_BATCH_SIZE_MB", "200")
) * 1024 * 1024
REQUIREMENT_UPLOAD_CHUNK_SIZE_BYTES = int(
    os.getenv("AI_TESTING_REQUIREMENT_UPLOAD_CHUNK_SIZE_MB", "5")
) * 1024 * 1024
REQUIREMENT_UPLOAD_CONCURRENCY = int(os.getenv("AI_TESTING_REQUIREMENT_UPLOAD_CONCURRENCY", "3"))
REQUIREMENT_UPLOAD_MAX_ACTIVE_SESSIONS_PER_USER = int(
    os.getenv("AI_TESTING_REQUIREMENT_UPLOAD_MAX_ACTIVE_SESSIONS_PER_USER", "2")
)
REQUIREMENT_UPLOAD_SESSION_TTL_HOURS = int(
    os.getenv("AI_TESTING_REQUIREMENT_UPLOAD_SESSION_TTL_HOURS", "24")
)

PLAYWRIGHT_RUNNER_DIR = Path(
    os.getenv("AI_TESTING_PLAYWRIGHT_RUNNER_DIR", BACKEND_ROOT / "runners" / "playwright")
).resolve()
PLAYWRIGHT_CLI_COMMAND = os.getenv("AI_TESTING_PLAYWRIGHT_CLI_COMMAND", "playwright")
PLAYWRIGHT_CLI_OPEN_TIMEOUT_SECONDS = int(
    os.getenv("AI_TESTING_PLAYWRIGHT_CLI_OPEN_TIMEOUT_SECONDS", "30")
)
PLAYWRIGHT_CLI_GOTO_TIMEOUT_SECONDS = int(
    os.getenv("AI_TESTING_PLAYWRIGHT_CLI_GOTO_TIMEOUT_SECONDS", "30")
)
PLAYWRIGHT_CLI_SNAPSHOT_TIMEOUT_SECONDS = int(
    os.getenv("AI_TESTING_PLAYWRIGHT_CLI_SNAPSHOT_TIMEOUT_SECONDS", "10")
)
PLAYWRIGHT_CLI_CLICK_TIMEOUT_SECONDS = int(
    os.getenv("AI_TESTING_PLAYWRIGHT_CLI_CLICK_TIMEOUT_SECONDS", "5")
)
PLAYWRIGHT_CLI_FILL_TIMEOUT_SECONDS = int(
    os.getenv("AI_TESTING_PLAYWRIGHT_CLI_FILL_TIMEOUT_SECONDS", "5")
)
PLAYWRIGHT_BROWSER_CHANNEL = os.getenv("AI_TESTING_PLAYWRIGHT_BROWSER_CHANNEL", "chrome")

PERFORMANCE_MAX_USERS = int(os.getenv("AI_TESTING_PERFORMANCE_MAX_USERS", "1000"))
PERFORMANCE_MAX_SPAWN_RATE = float(os.getenv("AI_TESTING_PERFORMANCE_MAX_SPAWN_RATE", "100"))
PERFORMANCE_MAX_DURATION_SECONDS = int(os.getenv("AI_TESTING_PERFORMANCE_MAX_DURATION_SECONDS", "3600"))
PERFORMANCE_MAX_CONCURRENT_RUNS = int(os.getenv("AI_TESTING_PERFORMANCE_MAX_CONCURRENT_RUNS", "2"))
