from fastapi import APIRouter

from app.api.v1 import agents, ai, auth, dashboard, documents, environments, global_knowledge, knowledge, models, operation_logs, page_exploration, projects, requirement_files, requirements, tasks, test_cases, users

v1_router = APIRouter()
v1_router.include_router(auth.router)
v1_router.include_router(dashboard.router)
v1_router.include_router(users.router)
v1_router.include_router(ai.router)
v1_router.include_router(ai.model_assignment_router)
v1_router.include_router(models.router)
v1_router.include_router(projects.router)
v1_router.include_router(operation_logs.router)
v1_router.include_router(operation_logs.project_router)
v1_router.include_router(environments.router)
v1_router.include_router(knowledge.global_router)
v1_router.include_router(knowledge.router)
v1_router.include_router(global_knowledge.router)
v1_router.include_router(requirements.global_router)
v1_router.include_router(requirements.router)
v1_router.include_router(requirement_files.router)
v1_router.include_router(test_cases.router)
v1_router.include_router(tasks.router)
v1_router.include_router(documents.router)
v1_router.include_router(agents.router)
v1_router.include_router(page_exploration.router)
